### ISSUE TITLE
nested interfaces

### ISSUE THREAD

**Issue by mvertes** [traefik/yaegi#1187]
### The following program `sample.go` triggers an unexpected result

```go
package main

import (
    "io"
    "os"
)

type sink interface {
    io.Writer
}

func newSink() sink { return os.Stdout }

func main() { 
    s := newSink()
    s.Write([]byte("Hello\n"))
}
```

### Expected result

```console
$ go run ./sample.go
Hello
```

### Got

```console
$ yaegi ./sample.go
/Users/marc/sample.go:16:2: panic
run: reflect: reflect.Value.Call using value obtained using unexported field
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0x14000260200, 0x40)
	/Users/marc/sdk/go1.16.6/src/runtime/debug/stack.go:24 +0x88
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0x140004d3bf0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:504 +0x94
panic(0x10376df20, 0x14000076af0)
	/Users/marc/sdk/go1.16.6/src/runtime/panic.go:965 +0x14c
github.com/traefik/yaegi/interp.runCfg.func1(0x140001dc210, 0x140001d4800, 0x140004d39c0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:185 +0x1e8
panic(0x10376df20, 0x14000076af0)
	/Users/marc/sdk/go1.16.6/src/runtime/panic.go:965 +0x14c
reflect.flag.mustBeExportedSlow(0x2b3)
	/Users/marc/sdk/go1.16.6/src/reflect/value.go:238 +0x114
reflect.flag.mustBeExported(...)
	/Users/marc/sdk/go1.16.6/src/reflect/value.go:229
reflect.Value.Call(0x1038487c0, 0x140000327c0, 0x2b3, 0x1400000e510, 0x1, 0x1, 0x140004d38c8, 0x10308e790, 0x1400000e401)
	/Users/marc/sdk/go1.16.6/src/reflect/value.go:336 +0x3c
github.com/traefik/yaegi/interp.callBin.func1(0x1038487c0, 0x140000327c0, 0x2b3, 0x1400000e510, 0x1, 0x1, 0x103764f60, 0x1400000e4e0, 0x197)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:1325 +0x50
github.com/traefik/yaegi/interp.callBin.func10(0x140001dc210, 0x1400018e870)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:1494 +0x168
github.com/traefik/yaegi/interp.runCfg(0x140001d4800, 0x140001dc210)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:191 +0x8c
github.com/traefik/yaegi/interp.(*Interpreter).run(0x1400036e000, 0x1400008fe00, 0x14000370000)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:122 +0x244
github.com/traefik/yaegi/interp.(*Interpreter).eval(0x1400036e000, 0x1400058a000, 0xf1, 0x16d0c37f0, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:596 +0x5e8
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0x1400036e000, 0x16d0c37f0, 0x16, 0x1400018c300, 0xf1, 0x0, 0x0, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:418 +0xc4
main.runFile(0x1400036e000, 0x16d0c37f0, 0x16, 0x0, 0x0, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:149 +0x84
main.run(0x140001c0010, 0x1, 0x1, 0x14000182480, 0x14000073ea8)
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:112 +0x830
main.main()
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:144 +0x324
```

### Yaegi Version

v0.9.19

**Comment by mvertes** [comment]
This bug is related to #1172
