### ISSUE TITLE
Deep closure appears to lose some of global scope and panics (worked before 25b570d)

### ISSUE THREAD

**Issue by TheMightyGit** [traefik/yaegi#1206]
### The following program `closure_losing_global_scope_somehow.go` triggers an unexpected result

```go
package main

import (
	"fmt"
	"image"
)

func DivP(a image.Point, b image.Point) image.Point {
	return image.Point{a.X / b.X, a.Y / b.Y}
}

type Event struct {
	pos image.Point
}

type UIComponent interface {
	HandleEvent(e *Event)
}

type Window struct {
	UIRoot UIComponent
}

func (w *Window) HandleEvent(e *Event) {
	w.UIRoot.HandleEvent(e)
}

func (w *Window) AddComponent(uic UIComponent) {
	w.UIRoot = uic
}

func NewWindow() *Window {
	w := &Window{
		UIRoot: NewUISprite(),
	}
	return w
}

type UISprite struct {
	OnMouseDown func(image.Point)
}

func (s *UISprite) HandleEvent(e *Event) {
	s.OnMouseDown(e.pos)
}

func NewUISprite() *UISprite {

	localNewCustomWindow := NewCustomWindow

	sp := &UISprite{
		OnMouseDown: func(pos image.Point) {
			newPos := DivP(pos, image.Point{8, 8}) // for some reason this global func is not a problem.
			fmt.Println(pos, newPos)
			_ = localNewCustomWindow() // <--- does NOT panic when using a local ref to NewCustomWindow.
			_ = NewCustomWindow()      // <--- panics! has closure lost global scope somehow???
		},
	}
	return sp
}

type WorkBench struct {
	windows []*Window
}

func (wb *WorkBench) AddWindow(w *Window) {
	wb.windows = append(wb.windows, w)
}

func (wb *WorkBench) HandleEvent(e *Event) {
	for _, w := range wb.windows {
		w.HandleEvent(e)
	}
}

func NewWorkBench() *WorkBench {
	return &WorkBench{}
}

func NewCustomWindow() *Window {
	win := NewWindow()
	sprite := NewUISprite()
	win.AddComponent(sprite)
	return win
}

var workBench = NewWorkBench()

func main() {
	// add initial window
	win := NewCustomWindow()
	workBench.AddWindow(win)

	workBench.HandleEvent(&Event{
		pos: image.Point{100, 100},
	})
}
```

### Expected result

```console
$ go run closure_losing_global_scope_somehow.go
(100,100) (12,12)
```

### Got

```console
$ yaegi closure_losing_global_scope_somehow.go
(100,100) (12,12)
closure_losing_global_scope_somehow.go:53:14: panic
closure_losing_global_scope_somehow.go:44:2: panic
closure_losing_global_scope_somehow.go:25:2: panic
closure_losing_global_scope_somehow.go:72:3: panic
closure_losing_global_scope_somehow.go:94:2: panic
run: reflect: call of reflect.Value.Call on ptr Value
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc000384800, 0x40)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc00054bc18)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/interp.go:505 +0xc8
panic(0x1a50ec0, 0xc0001ab818)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0001dedc0, 0xc000540200, 0xc00054b9f8)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:184 +0x253
panic(0x1a50ec0, 0xc0001ab818)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0001df6b0, 0xc00053c200, 0xc00054b7d0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:184 +0x253
panic(0x1a50ec0, 0xc0001ab818)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0001df810, 0xc00052e400, 0xc00054b5a8)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:184 +0x253
panic(0x1a50ec0, 0xc0001ab818)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0001df970, 0xc000532d00, 0xc00054b380)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:184 +0x253
panic(0x1a50ec0, 0xc0001ab818)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0001dfa20, 0xc000535800, 0xc00054ac98)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:184 +0x253
panic(0x1a50ec0, 0xc0001ab818)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
reflect.flag.mustBe(...)
        /usr/local/Cellar/go/1.16.5/libexec/src/reflect/value.go:221
reflect.Value.Call(0x1a00be0, 0xc0005368e0, 0x16, 0x21ee8a8, 0x0, 0x0, 0x10d4899, 0x1a3c840, 0xc00022e5f0)
        /usr/local/Cellar/go/1.16.5/libexec/src/reflect/value.go:335 +0x174
github.com/traefik/yaegi/interp.call.func6(0xc0001dfa20, 0xc0005508c0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:1176 +0x10c7
github.com/traefik/yaegi/interp.runCfg(0xc000535800, 0xc0001dfa20)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.genFunctionWrapper.func2.1(0xc0001ab7d0, 0x1, 0x1, 0xc0001ab7d0, 0x400, 0x2500a68)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:951 +0x3e8
reflect.Value.call(0xc0001b6fc0, 0xc0001b54e0, 0x193, 0x1b517f8, 0x4, 0xc0001ab7b8, 0x1, 0x1, 0x2500a01, 0xc00055afa0, ...)
        /usr/local/Cellar/go/1.16.5/libexec/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0001b6fc0, 0xc0001b54e0, 0x193, 0xc0001ab7b8, 0x1, 0x1, 0x1b4e7a0, 0x1b09c01, 0xc0001ab7b8)
        /usr/local/Cellar/go/1.16.5/libexec/src/reflect/value.go:337 +0xb9
github.com/traefik/yaegi/interp.callBin.func1(0xc0001b6fc0, 0xc0001b54e0, 0x193, 0xc0001ab7b8, 0x1, 0x1, 0xc00054b378, 0xc00054b350, 0x13e8287)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:1329 +0x65
github.com/traefik/yaegi/interp.callBin.func10(0xc0001df970, 0xc0005247d0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:1498 +0x1c2
github.com/traefik/yaegi/interp.runCfg(0xc000532d00, 0xc0001df970)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.call.func6(0xc0001df810, 0xc000550ee0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:1279 +0xdc5
github.com/traefik/yaegi/interp.runCfg(0xc00052e400, 0xc0001df810)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.call.func6(0xc0001df6b0, 0xc000550fc0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:1279 +0xdc5
github.com/traefik/yaegi/interp.runCfg(0xc00053c200, 0xc0001df6b0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.call.func6(0xc0001dedc0, 0xc000551180)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:1279 +0xdc5
github.com/traefik/yaegi/interp.runCfg(0xc000540200, 0xc0001dedc0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc0003f0000, 0xc00053fa00, 0xc0001de9a0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/run.go:121 +0x2b0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc0003f0000, 0xc000521500, 0x691, 0x7ffeefbffbce, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/interp.go:597 +0x80c
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc0003f0000, 0x7ffeefbffbce, 0x26, 0xc000520700, 0x691, 0x0, 0x0, 0xc000245cb0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/interp/interp.go:419 +0x105
main.runFile(0xc0003f0000, 0x7ffeefbffbce, 0x26, 0x0, 0x1, 0x0)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/cmd/yaegi/run.go:149 +0xb1
main.run(0xc0001b8010, 0x1, 0x1, 0xc00018c101, 0xc000182480)
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/cmd/yaegi/run.go:112 +0x9c5
main.main()
        /Users/johnny/go/pkg/mod/github.com/traefik/yaegi@v0.9.22-0.20210727085806-b41fa6eb9dac/cmd/yaegi/yaegi.go:144 +0x415
```

### Yaegi Version

25b570d7e9dcd62a8554d66ddeea6d074d838c1e

### Additional Notes

Works fine in: 297b40d5263f26503ecaf5430f34613e887fcf2b
Error from: 25b570d7e9dcd62a8554d66ddeea6d074d838c1e and continues to master

Sorry this is so complicated, I could not find a simpler repro so I had to base it on the code going wrong in my app (which has a windowing and ui event handling system).

**Comment by mvertes** [comment]
Fixed by.#1217.

**Comment by TheMightyGit** [comment]
I can confirm this fixes all associated errors in my app as well as the test case. Thank you. I very much appreciate it <3
