### ISSUE TITLE
setting interface from nested func call

### ISSUE THREAD

**Issue by mvertes** [traefik/yaegi#1320]
### The following program `sample.go` triggers an unexpected result

```go
package main
                                                                                
type Pooler interface {                                                         
    Get() string                                                                
}                                                                               
                                                                                
type baseClient struct {                                                        
    connPool Pooler                                                             
}                                                                               
                                                                                
type connPool struct {                                                          
    name string                                                                 
}                                                                               
                                                                                
func (c *connPool) Get() string { return c.name }                               
                                                                                
func newBaseClient(p Pooler) *baseClient {                                      
    return &baseClient{connPool: p}                                             
}                                                                               
                                                                                
func newConnPool() *connPool { return &connPool{name: "connPool"} }             

func main() {                                                                   
    b := newBaseClient(newConnPool())                                           
    println(b.connPool.(*connPool).name)                                        
}
```

### Expected result

```console
$ go run ./sample.go
connPool
```

### Got

```console
$ yaegi ./sample.go
/Users/marc/yt/call1.go:24:21: panic
run: reflect.Set: value of type *struct { Xname string } is not assignable to type interp.valueInterface
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/marc/sdk/go1.17.3/src/runtime/debug/stack.go:24 +0x88
github.com/traefik/yaegi/interp.(*Interpreter).Execute.func1(0x140001bbae0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/program.go:131 +0x8c
panic({0x104f8ecc0, 0x140001a38c0})
	/Users/marc/sdk/go1.17.3/src/runtime/panic.go:1038 +0x21c
github.com/traefik/yaegi/interp.runCfg.func1(0x140000d0bb0, 0x140004bec60, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:193 +0x164
panic({0x104f8ecc0, 0x140001a38c0})
	/Users/marc/sdk/go1.17.3/src/runtime/panic.go:1038 +0x21c
reflect.Value.assignTo({0x140001ceb40, 0x14000010b50, 0x196}, {0x104da9463, 0xb}, 0x1050075e0, 0x0)
	/Users/marc/sdk/go1.17.3/src/reflect/value.go:2797 +0x2cc
reflect.Value.Set({0x1050075e0, 0x14000033460, 0x199}, {0x140001ceb40, 0x14000010b50, 0x196})
	/Users/marc/sdk/go1.17.3/src/reflect/value.go:1905 +0xa4
github.com/traefik/yaegi/interp.call.func7(0x140000d0bb0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:1364 +0xb4c
github.com/traefik/yaegi/interp.runCfg(0x140004bec60, 0x140000d0bb0, 0x140004be120, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:201 +0x268
github.com/traefik/yaegi/interp.(*Interpreter).run(0x140000f9b00, 0x140004be120, 0x140000d0a50)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:120 +0x3d4
github.com/traefik/yaegi/interp.(*Interpreter).Execute(0x140000f9b00, 0x140004c5710)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/program.go:157 +0x1e0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0x140000f9b00, {0x140002ea780, 0x1c3}, {0x16b8eb728, 0x17}, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:615 +0x98
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0x140000f9b00, {0x16b8eb728, 0x17})
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:508 +0xe8
main.runFile(0x140000f9b00, {0x16b8eb728, 0x17}, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:154 +0xb0
main.run({0x14000032050, 0x1, 0x1})
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:117 +0xe14
main.main()
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:144 +0x384
```

### Yaegi Version

v0.11.0

**Comment by mvertes** [comment]
This issue is related to running redis client, as per #1294

**Comment by mvertes** [comment]
Note also that a workaround is to perform
```go
p := newConnPool()
b := newBaseClient(p)
```
instead of
```go
b := newBaseClient(newConnPool())
```
