### ISSUE TITLE
switch type on on interface case, with multi-types case

### ISSUE THREAD

**Issue by mpl** [traefik/yaegi#1322]
### The following program `sample.go` triggers an unexpected result

```go
package main

type Intf interface {
	M()
}

type T struct {
	s string
}

func (t *T) M() { println("in M") }

func f(i interface{}) {
	switch j := i.(type) {
	case string, int:
		println("string or int")
	case Intf:
		j.M()
	default:
		println("default")
	}
}

func main() {
	var i Intf
	var k interface{} = 1
	i = &T{"hello"}
	f(i)
	f(k)
}

// Output:
// in M
// default
```

### Expected result

```console
% go run ./_test/issue-1315.go
in M
string or int
```

### Got

```console
% yaegi run ./_test/issue-1315.go 
in M
./_test/issue-1315.go:14:2: panic
./_test/issue-1315.go:25:6: panic
run: interface conversion: interface {} is int, not interp.valueInterface
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/mpl/go1/src/runtime/debug/stack.go:24 +0x65
github.com/traefik/yaegi/interp.(*Interpreter).Execute.func1()
	/Users/mpl/src/github.com/traefik/yaegi/interp/program.go:131 +0x94
panic({0x1925120, 0xc000494c60})
	/Users/mpl/go1/src/runtime/panic.go:1038 +0x215
github.com/traefik/yaegi/interp.runCfg.func1()
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:193 +0x145
panic({0x1925120, 0xc000494c60})
	/Users/mpl/go1/src/runtime/panic.go:1038 +0x215
github.com/traefik/yaegi/interp.runCfg.func1()
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:193 +0x145
panic({0x1925120, 0xc000494c60})
	/Users/mpl/go1/src/runtime/panic.go:1038 +0x215
github.com/traefik/yaegi/interp._case.func5(0x1069dd9)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:2903 +0x1ea
github.com/traefik/yaegi/interp.runCfg(0xc000487e60, 0xc00035e4d0, 0x20, 0x18fdf00)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:201 +0x2ac
github.com/traefik/yaegi/interp.call.func6(0xc00035e210)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:1343 +0x94e
github.com/traefik/yaegi/interp.runCfg(0xc00048cb40, 0xc00035e210, 0xc00048c240, 0xc0001bda80)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:201 +0x2ac
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc00035c000, 0xc00048c240, 0xc00035e000)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:120 +0x385
github.com/traefik/yaegi/interp.(*Interpreter).Execute(0xc00035c000, 0xc0004945a0)
	/Users/mpl/src/github.com/traefik/yaegi/interp/program.go:157 +0x24b
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc00035c000, {0xc000480300, 0x174}, {0x7ffeefbff6fa, 0xc000480000}, 0x74)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:615 +0x5c
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc00035c000, {0x7ffeefbff6fa, 0x15})
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:508 +0xab
main.runFile(0x7ffeefbff6fa, {0x7ffeefbff6fa, 0x15}, 0x0)
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:154 +0x8f
main.run({0xc0000321d0, 0xc000000101, 0xc0000606b8})
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:117 +0xbec
main.main()
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:133 +0xd5
```

### Yaegi Version

master

### Additional Notes

Very similar to #1315 , and probably needs the same kind of fix, but for the "default" case of the switch len(types) , which deals with matching against multiple types.

**Comment by mvertes** [comment]
Does not reproduce anymore on master.
