### ISSUE TITLE
call of reflect.Value.Field on interface Value

### ISSUE THREAD

**Issue by XciD** [traefik/yaegi#1335]
### The following program `sample.go` triggers an unexpected result

```go
package main

type SomeStruct struct {
}

type Inter interface {
	Hello() string
	World() string
}

func (s *SomeStruct) Hello() string {
	return "world"
}

func (s *SomeStruct) World() string {
	return "world"
}

type AnotherStruct struct {
	Inter
	text string
}

func (s *AnotherStruct) World() string {
	return s.Hello()
}

func main () {
	someStruct := SomeStruct{}
	anotherStruct := AnotherStruct{&someStruct, "test"}
	println(anotherStruct.World())
}
```

### Expected result

```console
go run test.go
world
```

### Got

```console
yaegi run test.go
test.go:25:9: panic
test.go:29:16: panic
run: reflect: call of reflect.Value.Field on interface Value
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/debug/stack.go:24 +0x88
github.com/traefik/yaegi/interp.(*Interpreter).Execute.func1(0x1400024bae0)
	/home/runner/work/yaegi/yaegi/interp/program.go:131 +0x8c
panic({0x103a13080, 0x1400028a810})
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1038 +0x21c
github.com/traefik/yaegi/interp.runCfg.func1(0x140003dc210, 0x140005050e0, 0x0)
	/home/runner/work/yaegi/yaegi/interp/run.go:193 +0x164
panic({0x103a13080, 0x1400028a810})
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1038 +0x21c
github.com/traefik/yaegi/interp.runCfg.func1(0x140003dc370, 0x14000504480, 0x0)
	/home/runner/work/yaegi/yaegi/interp/run.go:193 +0x164
panic({0x103a13080, 0x1400028a810})
	/opt/hostedtoolcache/go/1.17.3/x64/src/runtime/panic.go:1038 +0x21c
reflect.Value.Field({0x103a09580, 0x140002892e0, 0x194}, 0x0)
	/opt/hostedtoolcache/go/1.17.3/x64/src/reflect/value.go:1185 +0x11c
reflect.Value.FieldByIndex({0x14000280660, 0x140002892e0, 0x199}, {0x1400028feb0, 0x2, 0x2})
	/opt/hostedtoolcache/go/1.17.3/x64/src/reflect/value.go:1229 +0xb0
github.com/traefik/yaegi/interp.getPtrIndexSeq.func2(0x140003dc370)
	/home/runner/work/yaegi/yaegi/interp/run.go:1999 +0x10c
github.com/traefik/yaegi/interp.runCfg(0x14000504480, 0x140003dc370, 0x140005066c0, 0x14000505e60)
	/home/runner/work/yaegi/yaegi/interp/run.go:201 +0x268
github.com/traefik/yaegi/interp.call.func9(0x140003dc210)
	/home/runner/work/yaegi/yaegi/interp/run.go:1387 +0x7c0
github.com/traefik/yaegi/interp.runCfg(0x140005050e0, 0x140003dc210, 0x140005047e0, 0x0)
	/home/runner/work/yaegi/yaegi/interp/run.go:201 +0x268
github.com/traefik/yaegi/interp.(*Interpreter).run(0x140003da000, 0x140005047e0, 0x140003dc000)
	/home/runner/work/yaegi/yaegi/interp/run.go:120 +0x3d4
github.com/traefik/yaegi/interp.(*Interpreter).Execute(0x140003da000, 0x1400050ea20)
	/home/runner/work/yaegi/yaegi/interp/program.go:157 +0x1e0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0x140003da000, {0x1400035e780, 0x1c8}, {0x16ce8f932, 0x7}, 0x0)
	/home/runner/work/yaegi/yaegi/interp/interp.go:615 +0x98
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0x140003da000, {0x16ce8f932, 0x7})
	/home/runner/work/yaegi/yaegi/interp/interp.go:508 +0xe8
main.runFile(0x140003da000, {0x16ce8f932, 0x7}, 0x0)
	/home/runner/work/yaegi/yaegi/cmd/yaegi/run.go:153 +0xb0
main.run({0x140001921a0, 0x1, 0x1})
	/home/runner/work/yaegi/yaegi/cmd/yaegi/run.go:116 +0xe14
main.main()
	/home/runner/work/yaegi/yaegi/cmd/yaegi/yaegi.go:133 +0xf4
```

### Yaegi Version

0.11.1

### Additional Notes

Hello,

I've tried to generify my issue here:

https://github.com/XciD/traefik-plugin-rewrite-headers/blob/42380a37031ed39ab12ad846598010d8c781d0b0/rewrite_headers.go

I've got this error with the code from the repo:
```
method not found: Header
```

Seems like the problem is on traefik 2.5.5, was working well on 2.5.0

**Comment by taliesins** [comment]
@XciD maybe we should change the title to something like "embedded types fail"
