### ISSUE TITLE
How do I call the method of the struct

### ISSUE THREAD

**Issue by lz520520** [traefik/yaegi#1346]
### The following program `sample.go` triggers an unexpected result

```go
package script

import (
	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
	"testing"
)


var (
	src2 = `
package plugins_test

import "fmt"



type Test struct {

}

func (t *Test) Run()  {
	fmt.Println("run")
}

`

	src3 = `package bar

type Foo struct {
	A string
}

func NewFoo() *Foo {
	return &Foo{A: "test"}
}`
)

func TestTest(t *testing.T) {
	intp := interp.New(interp.Options{})

	intp.Use(stdlib.Symbols)
	_, err := intp.Eval(src2)
	if err != nil {
		panic(err)
	}


	v, _ := intp.Eval("plugins_test.Run")
	v.MethodByName("Run")

}
```

### Expected result

```console
Here is the test of calling the structure method, mainly see the following error
```

### Got

```console
panic: reflect: call of reflect.Value.MethodByName on zero Value [recovered]
    panic: reflect: call of reflect.Value.MethodByName on zero Value

goroutine 20 [running]:
testing.tRunner.func1.2(0x1040dc0, 0xc0000b46c0)
    /go/src/testing/testing.go:1143 +0x345
testing.tRunner.func1(0xc00008c480)
    /go/src/testing/testing.go:1146 +0x4b6
panic(0x1040dc0, 0xc0000b46c0)
    /go/src/runtime/panic.go:965 +0x1c7
reflect.Value.MethodByName(0x0, 0x0, 0x0, 0x1150551, 0x3, 0x1, 0x0, 0x0)
    /go/src/reflect/value.go:1354 +0x205
go-gui/pkg/script.TestTest(0xc00008c480)
    E:/code/go/go-gui/pkg/script/script_test.go:51 +0x19d
testing.tRunner(0xc00008c480, 0x119d120)
    /go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
    /go/src/testing/testing.go:1238 +0x2b3


Process finished with the exit code 1
```

### Yaegi Version

v0.11.2

### Additional Notes

I want to call the method of this structure, but it seems that I can’t get the method

**Comment by Lcys** [comment]
Has the landlord found a solution?

**Comment by Beanzilla** [comment]
Looks like [https://github.com/traefik/yaegi/blob/master/example/getfunc/getfunc_test.go#L26](https://github.com/traefik/yaegi/blob/master/example/getfunc/getfunc_test.go#L26) might be what you want to try out.
