### ISSUE TITLE
SIGSEGV in gta/definedType when referring to non-existing identifier/type

### ISSUE THREAD

**Issue by torbenschinke** [traefik/yaegi#1369]
### The following program `sample.go` triggers an unexpected result

```go
package main

import (
  	"some_pkg"
)

type SomeStruct struct{
   SomeField some_pkg.Unknown_Ident
}

func main() {

}
```

### Expected result

```console
_some_pkg.Unknown_Ident is undefined_ or the panic should be at least recoverable
```

### Got

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0xe8 pc=0x104f890ec]

goroutine 5 [running]:
github.com/traefik/yaegi/interp.definedType(0x10512d660?)
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/gta.go:379 +0x1c
github.com/traefik/yaegi/interp.(*Interpreter).gtaRetry(0x140001406c0?, {0x14000195ed0?, 0x1400016a480?, 0x14000195e10?}, {0x1400001e858, 0x4}, {0x1400001e858, 0x4})
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/gta.go:365 +0x21c
github.com/traefik/yaegi/interp.(*Interpreter).CompileAST(0x140001406c0, {0x1051482a0?, 0x1400016a480?})
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/program.go:77 +0x124
github.com/traefik/yaegi/interp.(*Interpreter).compileSrc(0x140001406c0, {0x1050325c0?, 0x30647d2000000000?}, {0x0?, 0x14000047f58?}, 0x4c?)
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/program.go:52 +0xe4
github.com/traefik/yaegi/interp.(*Interpreter).eval(0x140001406c0, {0x1050325c0?, 0x104df4820?}, {0x0?, 0x104df4870?}, 0xa0?)
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/interp.go:606 +0x2c
github.com/traefik/yaegi/interp.(*Interpreter).Eval(...)
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/interp.go:492
github.com/traefik/yaegi/interp.(*Interpreter).EvalWithContext.func1()
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/interp.go:632 +0x78
created by github.com/traefik/yaegi/interp.(*Interpreter).EvalWithContext
	/Users/tschinke/go/pkg/mod/github.com/traefik/yaegi@v0.11.2/interp/interp.go:630 +0x184
```

### Yaegi Version

v0.11.2

### Additional Notes

Note, that there must be a declared interp.Export like 

```go
myExports := interp.Exports{}
myExports["some_pkg/some_pkg"] = map[string]reflect.Value{}
```
Even more problematic for us is, that it is not possible to recover from that panic, due to the extra go routine in EvalWithContext (seems similar but not equal to #487).

**Comment by mvertes** [comment]
I tried to run the example provided above using the most recent yaegi executable (v0.11.3), and I got the following:

```console
$ yaegi run ./sample.go
run: ./sample.go:4:2: import "some_pkg" error: unable to find source related to: "some_pkg"
```

Which is what is expected in the case `some_pkg` doesn't exist. No problem here.

I also do not understand your additional notes. Have you built a custom interpreter ?

**Comment by torbenschinke** [comment]
Yes, you are right. This is a custom interpreter instance. Here is a unit test:

```go
func TestYaegi(t *testing.T) {
	ip := interp.New(interp.Options{})
	myExports := interp.Exports{}
	myExports["some_pkg/some_pkg"] = map[string]reflect.Value{}
	if err := ip.Use(myExports); err != nil {
		t.Fatal(err)
	}

	_, err := ip.EvalWithContext(context.Background(), `
package main

import (
  	"some_pkg"
)

type SomeStruct struct{
   SomeField some_pkg.Unknown_Ident
}

func main() {

}

`)

	if err != nil {
		panic(fmt.Errorf("this does not happen either: %w", err))
	}
}
```
This also happens using the latest `github.com/traefik/yaegi v0.11.3` version.
