### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by bbluo** [traefik/yaegi#1440]
### The following program `sample.go` triggers an unexpected result

```go
package main

import (
	"bytes"
	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
	"github.com/traefik/yaegi/stdlib/unrestricted"
	"github.com/traefik/yaegi/stdlib/unsafe"
	"log"
	"path/filepath"
)

func main() {
	goPath, err := filepath.Abs(filepath.FromSlash("../../"))
	if err != nil {
		log.Fatal(err)
	}

	var stdout, stderr bytes.Buffer
	i := interp.New(interp.Options{GoPath: goPath, Stdout: &stdout, Stderr: &stderr})
	// Use binary standard library
	if err = i.Use(stdlib.Symbols); err != nil {
		log.Fatal(err)
	}
	i.Use(unrestricted.Symbols)
	i.Use(unsafe.Symbols)

	if _, err = i.EvalPath(filepath.FromSlash("../robot/main.go")); err != nil {
		log.Fatal(err)
	}
	msg := stdout.String()
	log.Println(msg)
}
```

### Expected result

```console
true
```

### Got

```console
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/traefik/yaegi/interp.(*node).lastChild(...)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/cfg.go:2652
github.com/traefik/yaegi/interp.(*Interpreter).cfg.func1(0xc000135c20)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/cfg.go:267 +0x3a05
github.com/traefik/yaegi/interp.(*node).Walk(0xc000135c20, 0xc0011e1f88, 0xc0011e1fd0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:288 +0x34
github.com/traefik/yaegi/interp.(*node).Walk(0xc00012cd80, 0xc0011e1f88, 0xc0011e1fd0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*node).Walk(0xc00012c6c0, 0xc0011e1f88, 0xc0011e1fd0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*node).Walk(0xc00053e6c0, 0xc0011e1f88, 0xc0011e1fd0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*node).Walk(0xc00052ad80, 0xc0011e1f88, 0xc0011e1fd0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*node).Walk(0xc00052a5a0, 0xc0011e1f88, 0xc0011e1fd0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*Interpreter).cfg(0xc0003b2000, 0xc00052a5a0, 0xc000252510, {0xc0000401c1, 0x17}, {0xc000039990, 0x4})
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/cfg.go:62 +0x2b4
github.com/traefik/yaegi/interp.(*Interpreter).importSrc(0xc0003b2000, {0xc00003f6b0, 0x26}, {0xc0000401c1, 0x17}, 0x1)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/src.go:125 +0x6d6
github.com/traefik/yaegi/interp.(*Interpreter).gta.func1(0xc0004e6a20)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/gta.go:261 +0x20ea
github.com/traefik/yaegi/interp.(*node).Walk(0xc0004e6a20, 0xc0011e2d80, 0x0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:288 +0x34
github.com/traefik/yaegi/interp.(*node).Walk(0xc0004e6240, 0xc0011e2d80, 0x0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*node).Walk(0xc0004e6000, 0xc0011e2d80, 0x0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*Interpreter).gta(0xc0003b2000, 0xc0004e6000, {0xc00003f6b0, 0x26}, {0xc000040081, 0x19}, {0xc000038f87, 0x7})
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/gta.go:20 +0x22b
github.com/traefik/yaegi/interp.(*Interpreter).importSrc(0xc0003b2000, {0xc0000389c8, 0x4}, {0xc000040081, 0x19}, 0x1)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/src.go:108 +0x100a
github.com/traefik/yaegi/interp.(*Interpreter).gta.func1(0xc0003c2a20)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/gta.go:261 +0x20ea
github.com/traefik/yaegi/interp.(*node).Walk(0xc0003c2a20, 0xc0011e3b48, 0x0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:288 +0x34
github.com/traefik/yaegi/interp.(*node).Walk(0xc0003c26c0, 0xc0011e3b48, 0x0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*node).Walk(0xc0003c2480, 0xc0011e3b48, 0x0)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:292 +0x75
github.com/traefik/yaegi/interp.(*Interpreter).gta(0xc0003b2000, 0xc0003c2480, {0xc0000389c8, 0x4}, {0xc0000389c8, 0x4}, {0xc0000389c8, 0x4})
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/gta.go:20 +0x22b
github.com/traefik/yaegi/interp.(*Interpreter).gtaRetry(0xc0003b2000?, {0xc0004abd28?, 0xc00009e480?, 0xc0004abc70?}, {0xc0000389c8, 0x4}, {0xc0000389c8, 0x4})
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/gta.go:383 +0x155
github.com/traefik/yaegi/interp.(*Interpreter).CompileAST(0xc0003b2000, {0x1bd0378?, 0xc00009e480?})
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/program.go:87 +0x17f
github.com/traefik/yaegi/interp.(*Interpreter).compileSrc(0xc0003b2000, {0xc00049e700?, 0x0?}, {0x1a0daf8?, 0xc00049e700?}, 0xc3?)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/program.go:59 +0xb8
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc0003b2000, {0xc00049e700?, 0x6c3?}, {0x1a0daf8?, 0x0?}, 0xff?)
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:612 +0x28
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc0003b2000, {0x1a0daf8, 0x10})
        /Users/luotuquan/Desktop/develop/go/pkg/mod/github.com/traefik/yaegi@v0.14.1/interp/interp.go:514 +0xab
main.main()
        /Users/luotuquan/Desktop/develop/go/src/yaegi/main.go:28 +0x1e6
exit status 2
```

### Yaegi Version

0.14.1

**Comment by ldez** [comment]
Hello,
can you provide the code from `../robot/main.go` that produces the panic?

**Comment by bbluo** [comment]
> 你好， 你能提供`../robot/main.go`产生恐慌的代码吗？

Sorry, there's too much code, and it's private

**Comment by bbluo** [comment]
> Hello, can you provide the code from `../robot/main.go` that produces the panic?

Sorry, there's too much code, and it's private

**Comment by ldez** [comment]
can you extract a snippet with the code that produces the error?

Without any source code, your issue is mainly impossible to debug and fix.
