### ISSUE TITLE
yaegi REPL - runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by mardukbp** [traefik/yaegi#819]
Steps to reproduce:

1. `go get -u github.com/containous/yaegi/cmd/yaegi`
2. `yaegi`
3. Enter the following:

 ```go
func g(y int) {
return y
}
```

Expected result:

```
too many arguments to return
        have (int)
        want ()
```

Actual result:
```console
% yaegi
> func g(y int) {
return y
}
runtime error: index out of range [0] with length 0
goroutine 25 [running]:
runtime/debug.Stack(0x1, 0xc0002e0600, 0x40)
	/Users/mpl/go1/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).eval.func1(0xc000171f78)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:362 +0xbc
panic(0x1a08760, 0xc0003ae180)
	/Users/mpl/go1/src/runtime/panic.go:967 +0x15d
github.com/containous/yaegi/interp._return(0xc0003b0b00)
	/Users/mpl/src/github.com/containous/yaegi/interp/run.go:1839 +0x64f
github.com/containous/yaegi/interp.setExec.func1(0xc0003b0b00)
	/Users/mpl/src/github.com/containous/yaegi/interp/cfg.go:2350 +0xb2
github.com/containous/yaegi/interp.setExec(0xc0003b0b00)
	/Users/mpl/src/github.com/containous/yaegi/interp/cfg.go:2353 +0xf5
github.com/containous/yaegi/interp.genRun.func1(0xc0003b0500, 0x101)
	/Users/mpl/src/github.com/containous/yaegi/interp/cfg.go:1906 +0x87
github.com/containous/yaegi/interp.(*node).Walk(0xc0003b0500, 0xc000171e20, 0x0)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:197 +0xc9
github.com/containous/yaegi/interp.(*node).Walk(0xc0003b0200, 0xc000171e20, 0x0)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:201 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc0003b0000, 0xc000171e20, 0x0)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:201 +0x70
github.com/containous/yaegi/interp.genRun(0xc0003b0000, 0xc0002feb10, 0xc00033fc08)
	/Users/mpl/src/github.com/containous/yaegi/interp/cfg.go:1898 +0x60
github.com/containous/yaegi/interp.(*Interpreter).eval(0xc0002261a0, 0xc0003ae120, 0x1b, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:433 +0x58e
github.com/containous/yaegi/interp.(*Interpreter).Eval(...)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:335
github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext.func1(0xc0002b58c0, 0xc0002261a0, 0xc0003ae120, 0x1b, 0xc000204b60, 0xc000206300)
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:483 +0x84
created by github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext
	/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:481 +0x14d
```

**Comment by mardukbp** [comment]
Perfect! Thank you
