### ISSUE TITLE
interp: cannot type assert empty interface populated by json into slice

### ISSUE THREAD

**Issue by sh0rez** [traefik/yaegi#829]
The following program `panic.go` triggers a panic:

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
)

const jsonData = `[
  {"foo": "foo"},
  {"bar": "bar"}
]`

func main() {
	var a interface{}

	if err := json.Unmarshal([]byte(jsonData), &a); err != nil {
		log.Fatalln(err)
	}

	fmt.Printf("%T\n", a)
	b := a.([]interface{})

	for _, v := range b {
		fmt.Println(v)
	}
}

```

Expected result:
```console
$ go run ./panic.go
[]interface {}
map[foo:foo]
map[bar:bar]
```

Got:
```console
$ yaegi ./panic.go
panic.go:15:6: panic
reflect.Set: value of type *interp.valueInterface is not assignable to type *interface {}
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc000370600, 0x40)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9f
github.com/containous/yaegi/interp.(*Interpreter).eval.func1(0xc00028bcb0)
	/home/sh0rez/work/yaegi/interp/interp.go:362 +0xc5
panic(0xda4fe0, 0xc000114e60)
	/usr/lib/go/src/runtime/panic.go:969 +0x175
github.com/containous/yaegi/interp.runCfg.func1(0xc0003ea0a0, 0xc000127600)
	/home/sh0rez/work/yaegi/interp/run.go:123 +0x217
panic(0xda4fe0, 0xc000114e60)
	/usr/lib/go/src/runtime/panic.go:969 +0x175
reflect.Value.assignTo(0xd86c60, 0xc00011d4c0, 0x16, 0xed8d6d, 0xb, 0xd88ce0, 0x0, 0x4d0a56, 0xe25040, 0xd86c60)
	/usr/lib/go/src/reflect/value.go:2425 +0x405
reflect.Value.Set(0xd88ce0, 0xc00011a248, 0x196, 0xd86c60, 0xc00011d4c0, 0x16)
	/usr/lib/go/src/reflect/value.go:1554 +0xbd
github.com/containous/yaegi/interp.addr.func1(0xc0003ea0a0, 0xc00011d300)
	/home/sh0rez/work/yaegi/interp/run.go:523 +0xba
github.com/containous/yaegi/interp.runCfg(0xc000127600, 0xc0003ea0a0)
	/home/sh0rez/work/yaegi/interp/run.go:129 +0x6e
github.com/containous/yaegi/interp.(*Interpreter).run(0xc00013e1a0, 0xc000126e00, 0xc0003ea000)
	/home/sh0rez/work/yaegi/interp/run.go:107 +0x2af
github.com/containous/yaegi/interp.(*Interpreter).eval(0xc00013e1a0, 0xc000368420, 0x148, 0x7ffff85db470, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/sh0rez/work/yaegi/interp/interp.go:454 +0x75c
github.com/containous/yaegi/interp.(*Interpreter).EvalPath(0xc00013e1a0, 0x7ffff85db470, 0x8, 0xc000368200, 0x148, 0x0, 0x0, 0xc00028bd68)
	/home/sh0rez/work/yaegi/interp/interp.go:346 +0xd5
main.runFile(0xc00013e1a0, 0x7ffff85db470, 0x8, 0xc00010e180, 0x1)
	/home/sh0rez/work/yaegi/cmd/yaegi/run.go:122 +0x1c8
main.run(0xc00000e090, 0x1, 0x1, 0xf12938, 0xdb6860)
	/home/sh0rez/work/yaegi/cmd/yaegi/run.go:80 +0x7cc
main.main()
	/home/sh0rez/work/yaegi/cmd/yaegi/yaegi.go:128 +0x29b
```

**Comment by mpl** [comment]
Slightly simpler example, since json encoding/decoding could bring its own source of problems:

```go
package main

import (
	"fmt"
)

func main() {
	var a, b, c interface{}
	b = 2
	c = 3
	a = []interface{}{b, c}

	fmt.Printf("%T\n", a)
	d := a.([]interface{})

	for _, v := range d {
		fmt.Println(v)
	}
}
```

```console
run: reflect.Set: value of type []interp.valueInterface is not assignable to type interp.valueInterface
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0002fe600, 0x40)
	/Users/mpl/go1/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc0001c3c70)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:480 +0xc5
panic(0x19c11c0, 0xc00009cd80)
	/Users/mpl/go1/src/runtime/panic.go:969 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0003b00a0, 0xc0000b2e00, 0xc0001c3a60)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:184 +0x247
panic(0x19c11c0, 0xc00009cd80)
	/Users/mpl/go1/src/runtime/panic.go:969 +0x1b9
reflect.Value.assignTo(0x19b4f40, 0xc00009f600, 0x97, 0x1afb136, 0xb, 0x1a43620, 0x0, 0x1a43620, 0xc00009f680, 0x99)
	/Users/mpl/go1/src/reflect/value.go:2425 +0x405
reflect.Value.Set(0x1a43620, 0xc00009f560, 0x199, 0x19b4f40, 0xc00009f600, 0x97)
	/Users/mpl/go1/src/reflect/value.go:1554 +0xbd
github.com/traefik/yaegi/interp.arrayLit.func1(0xc0003b00a0, 0xc00037d570)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:2149 +0x225
github.com/traefik/yaegi/interp.runCfg(0xc0000b2e00, 0xc0003b00a0)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc00037a000, 0xc0000b2600, 0xc0003b0000)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:121 +0x2af
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc00037a000, 0xc0002f2270, 0xcd, 0x7ffeefbff6ca, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:572 +0x809
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc00037a000, 0x7ffeefbff6ca, 0x16, 0xc0002f2100, 0xcd, 0x0, 0x0, 0xc0000ab1e0)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:394 +0xfa
main.runFile(0xc00037a000, 0x7ffeefbff6ca, 0x16, 0xc0000963c0, 0x1)
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:123 +0xae
main.run(0xc0000321d0, 0x1, 0x1, 0x13, 0x13)
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:89 +0x7e5
main.main()
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:133 +0x479
```

**Comment by mpl** [comment]
Related to #984 and #985 

the program as described initially fails because of at least these two issues above. I have changed the title because it was only about one of the issues ( #985 ). There may be more underlying issues (related to json decoding maybe?), but we won't know until at least these two are fixed.
