### ISSUE TITLE
Interface conversion: assertion panic

### ISSUE THREAD

**Issue by ldez** [traefik/yaegi#91]
The following program `sample.go` triggers a panic:

```go
package main

import "fmt"

type Root struct {
	Name string
}

func (r *Root) Hello() {
	fmt.Println("Hello", r.Name)
}

type One Root

type Hi interface {
	Hello()
}

func main() {

	var root interface{} = &Root{Name: "test"}
	var one interface{} = &One{Name: "test"}

	fmt.Println(root.(Hi))
	fmt.Println(one.(Hi)) // panic
}

```

Expected result:
```console
$ go run ./sample.go
&{test}
panic: interface conversion: *main.One is not main.Hi: missing method Hello

goroutine 1 [running]:
main.main()
	/home/ldez/sources/go/src/github.com/containous/dyngo/_test/type8.go:25 +0x124
exit status 2
```

Got:
```console
$ dyngo ./sample.go
panic: reflect: call of reflect.Append on struct Value [recovered]
	panic: reflect: call of reflect.Append on struct Value

goroutine 1 [running]:
github.com/containous/dyngo/interp.runCfg.func1(0xc00009dd10)
	/home/ldez/sources/go/src/github.com/containous/dyngo/interp/run.go:103 +0x134
panic(0xbdc840, 0xc00000dd00)
	/home/ldez/.gvm/gos/go1.11.5/src/runtime/panic.go:513 +0x1b9
reflect.flag.mustBe(0x199, 0x17)
	/home/ldez/.gvm/gos/go1.11.5/src/reflect/value.go:207 +0xb4
reflect.Append(0xc000081920, 0xc000146e40, 0x199, 0xc0001e1d10, 0x1, 0x1, 0xc000218040, 0xc000146ed0, 0x16)
	/home/ldez/.gvm/gos/go1.11.5/src/reflect/value.go:1891 +0x3e
github.com/containous/dyngo/interp.arrayLit.func2(0xc00009dd10, 0xc0002180c0)
	/home/ldez/sources/go/src/github.com/containous/dyngo/interp/run.go:944 +0x11d
github.com/containous/dyngo/interp.runCfg(0xc0002179e0, 0xc00009dd10)
	/home/ldez/sources/go/src/github.com/containous/dyngo/interp/run.go:108 +0x62
github.com/containous/dyngo/interp.(*Interpreter).run(0xc0000d0700, 0xc000216ea0, 0xc00009dcc0)
	/home/ldez/sources/go/src/github.com/containous/dyngo/interp/run.go:90 +0xa6
github.com/containous/dyngo/interp.(*Interpreter).Eval(0xc0000d0700, 0xc0001ca000, 0x198, 0xca583f, 0x4, 0xc0000d0700, 0x0, 0x115f2e0)
	/home/ldez/sources/go/src/github.com/containous/dyngo/interp/interp.go:236 +0x4c3
main.main()
	/home/ldez/sources/go/src/github.com/containous/dyngo/dyngo.go:50 +0x334
exit status 2

```

**Comment by mvertes** [comment]
Tested with yaegi-v0.9.3 and the output is now:
```console
$ yaegi ~/yt/issue-91.go 
&{test}
/home/marc/yt/issue-91.go:21:11: panic
run: /home/marc/yt/issue-91.go:25:14: interface conversion: *main.One is not main.Hi
[ ... ]
```

which is what is expected, except the details of missing method is not given, and the stack dump is different (due to interpreter context). So it can be closed.
