### ISSUE TITLE
panic: interface conversion: struct {} is not io.Writer: missing method Write

### ISSUE THREAD

**Issue by chabad360** [traefik/yaegi#979]
The following program `sample.go` triggers a panic:

```go
package main

import (
	"fmt"
	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
	"io"
	"reflect"
)

func initPlugin() (interface{}, error) {
	i := interp.New(interp.Options{})
	i.Use(stdlib.Symbols)

	_, err := i.Eval(`import (
	"fmt"
	"io"
	"reflect"
)

type TestStruct struct{}

func (t TestStruct) Write(p []byte) (n int, err error) {
	fmt.Println(len(p))
	return len(p), nil
}

var TestS = TestStruct{}

func TestFunc() {
	aType := reflect.TypeOf((*io.Writer)(nil)).Elem()
	bType := reflect.TypeOf(TestS)

	fmt.Println("inside:", bType.Implements(aType))
}`)
	if err != nil {
		return nil, err
	}

	i.Eval("TestFunc()")

	i.Eval("TestS.Write(nil)")

	v, err := i.Eval("TestS")
	if err != nil {
		return nil, err
	}

	return v.Interface(), nil
}

func TestFunc(s interface{}) {
	aType := reflect.TypeOf((*io.Writer)(nil)).Elem()
	bType := reflect.TypeOf(s)

	fmt.Println("outside:", bType.Implements(aType))
}
func main() {
	t, err := initPlugin()
	if err != nil {
		fmt.Println(err)
	}
	TestFunc(t)
	t.(io.Writer).Write(nil)
}
```

Expected result:
```console
$ go run ./sample.go
inside: true
0
outside: true
0
```

Got:
```console
$ go run ./sample.go
inside: false
0
outside: false
panic: interface conversion: struct {} is not io.Writer: missing method Write

goroutine 1 [running]:
main.main()
        sample.go:64 +0xd4
exit status 2

```

If I explicitly specify the type with:

```go
type TestStruct struct{
    io.Writer
}
```

Then the output is:
```console
$ go run ./sample.go
inside: true
0
outside: true
unexpected fault address 0xc0002074e0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc0002074e0 pc=0xc0002074e0]

goroutine 1 [running]:
runtime.throw(0xe66a08, 0x5)
        /usr/lib/go/src/runtime/panic.go:1116 +0x72 fp=0xc00022bee8 sp=0xc00022beb8 pc=0x43cb32
runtime.sigpanic()
        /usr/lib/go/src/runtime/signal_unix.go:749 +0x405 fp=0xc00022bf18 sp=0xc00022bee8 pc=0x453645
main.main()
        sample.go:67 +0xf9 fp=0xc00022bf88 sp=0xc00022bf18 pc=0xcdc059
runtime.main()
        /usr/lib/go/src/runtime/proc.go:204 +0x209 fp=0xc00022bfe0 sp=0xc00022bf88 pc=0x43f3e9
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00022bfe8 sp=0xc00022bfe0 pc=0x476981
exit status 2
```

**Comment by mpl** [comment]
> Expected result:
> 
> ```
> $ go run ./sample.go
> inside: true
> 0
> 0
> outside: true
> 0
> ```
> 
> Got:
> 
> ```
> $ go run ./sample.go
> inside: false

yes, we know about this limitation. The internal representation we're using for objects that implement interfaces (e.g. structs) isn't compatible with the way reflect checks things in `Implements()`, so using reflect.Implements for a runtime method on an object that is coming from the interpreter is never going to work for now. That is why we added:

https://github.com/traefik/yaegi/commit/2db4579b6f40aa2d6a8aac13101e58a9917629ef#diff-73bee77a0f39fbfe81deee30a949e6a4a72cc781f3e497c3854bc59a80d260b8R49-R51

There probably are at least two ways to fix that, but we don't think any of them is trivial for now, so we need to think harder on that.

> 0
> 0
> outside: false
> panic: interface conversion: struct {} is not io.Writer: missing method Write
> 
> goroutine 1 [running]:
> main.main()
>         sample.go:70 +0xd4
> exit status 2
> ```
> 
> If I explicitly specify the type with:
> 
> ```go
> type TestStruct struct{
>     io.Writer
> }
> ```
> 
> Then the output is:
> 
> ```
> $ go run ./sample.go
> inside: true
> 0
> 0
> outside: true
> unexpected fault address 0xc0002096c0
> fatal error: fault
> [signal SIGSEGV: segmentation violation code=0x2 addr=0xc0002096c0 pc=0xc0002096c0]

Ok, I need to check further what is going on here. More on that later.
We might have to open two separate issues for clarity, we'll see.

> goroutine 1 [running]:
> runtime.throw(0xe66a08, 0x5)
>         /usr/lib/go/src/runtime/panic.go:1116 +0x72 fp=0xc00022bee8 sp=0xc00022beb8 pc=0x43cb32
> runtime.sigpanic()
>         /usr/lib/go/src/runtime/signal_unix.go:749 +0x405 fp=0xc00022bf18 sp=0xc00022bee8 pc=0x453645
> main.main()
>         sample.go:73 +0xf9 fp=0xc00022bf88 sp=0xc00022bf18 pc=0xcdc399
> runtime.main()
>         /usr/lib/go/src/runtime/proc.go:204 +0x209 fp=0xc00022bfe0 sp=0xc00022bf88 pc=0x43f3e9
> runtime.goexit()
>         /usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00022bfe8 sp=0xc00022bfe0 pc=0x476981
> exit status 2
> ```

**Comment by chabad360** [comment]
> yes, we know about this limitation. The internal representation we're using for objects that implement interfaces (e.g. structs) isn't compatible with the way reflect checks things in Implements(), so using reflect.Implements for a runtime method on an object that is coming from the interpreter is never going to work for now.

I don't really mind that (now that generics are coming, I can just do a type check), although it is problematic for now. I simply put that in there to better demonstrate the issue.

> Ok, I need to check further what is going on here. More on that later.
We might have to open two separate issues for clarity, we'll see.

I am curious if the fix for this could be the fix for `reflect.Implements` (at least when outside the interpreter). It seems that the issue is the same.

**Comment by mpl** [comment]
> If I explicitly specify the type with:
> 
> ```go
> type TestStruct struct{
>     io.Writer
> }
> ```

btw, what exactly do you mean with the above? where do you specify it? Can you provide us with the full code to obtain the panic below?

> Then the output is:
> 
> ```
> $ go run ./sample.go
> inside: true
> 0
> 0
> outside: true
> unexpected fault address 0xc0002096c0
> fatal error: fault
> [signal SIGSEGV: segmentation violation code=0x2 addr=0xc0002096c0 pc=0xc0002096c0]
> 
> goroutine 1 [running]:
> runtime.throw(0xe66a08, 0x5)
>         /usr/lib/go/src/runtime/panic.go:1116 +0x72 fp=0xc00022bee8 sp=0xc00022beb8 pc=0x43cb32
> runtime.sigpanic()
>         /usr/lib/go/src/runtime/signal_unix.go:749 +0x405 fp=0xc00022bf18 sp=0xc00022bee8 pc=0x453645
> main.main()
>         sample.go:73 +0xf9 fp=0xc00022bf88 sp=0xc00022bf18 pc=0xcdc399
> runtime.main()
>         /usr/lib/go/src/runtime/proc.go:204 +0x209 fp=0xc00022bfe0 sp=0xc00022bf88 pc=0x43f3e9
> runtime.goexit()
>         /usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00022bfe8 sp=0xc00022bfe0 pc=0x476981
> exit status 2
> ```

**Comment by mpl** [comment]
Related to #681 btw.

**Comment by chabad360** [comment]
> btw, what exactly do you mean with the above? where do you specify it? Can you provide us with the full code to obtain the panic below?

Oops, sorry about the lack of clarity, I meant if I explicitly added the interface to the type definition (on line 21), then the following happened. I've updated the OP to be more clear.

**Comment by chabad360** [comment]
Should I modify this issue to remove the part with `reflect.Implements`, and then you guys would move the "known limitation" label to #681 (for clarity's sake)?

**Comment by mpl** [comment]
@chabad360 sorry, I can't focus on this issue at the moment, so I don't know for sure. That said, if you have more precisely identified an issue, with an easier/smaller reproduction, that has nothing to do with reflect.Implements, then sure, feel free to clarify here what the issue is.

**Comment by chabad360** [comment]
I've removed the `reflect.Implements` portion.

**Comment by chabad360** [comment]
Should be able to remove the `Known limitation` tag now.
