### ISSUE TITLE
interp: panic when getting address of empty interface

### ISSUE THREAD

**Issue by mpl** [traefik/yaegi#984]
The following program `sample.go` triggers a panic:

```go
package main

func main() {
	var a interface{}

	println(&a)
}
```

Expected result:
```console
$ go run ./sample.go
0xc00003c768
```

Got:
```console
$ yaegi ./sample.go
./sample.go:6:10: panic
run: reflect: call of reflect.Value.Interface on zero Value
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0002d4600, 0x40)
	/Users/mpl/go1/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc000115c70)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:480 +0xc5
panic(0x19f5340, 0xc00000ee20)
	/Users/mpl/go1/src/runtime/panic.go:969 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc00035a0a0, 0xc000456a00, 0xc000115a60)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:184 +0x247
panic(0x19f5340, 0xc00000ee20)
	/Users/mpl/go1/src/runtime/panic.go:969 +0x1b9
reflect.valueInterface(0x0, 0x0, 0x0, 0x101, 0x1a43620, 0xc00000ee00)
	/Users/mpl/go1/src/reflect/value.go:1020 +0x1ad
reflect.Value.Interface(...)
	/Users/mpl/go1/src/reflect/value.go:1015
github.com/traefik/yaegi/interp.addr.func1(0xc00035a0a0, 0xc00042c990)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:682 +0xf9
github.com/traefik/yaegi/interp.runCfg(0xc000456a00, 0xc00035a0a0)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc000354000, 0xc000456200, 0xc00035a000)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:121 +0x2af
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc000354000, 0xc00003c7c0, 0x40, 0x7ffeefbff6da, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:572 +0x809
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc000354000, 0x7ffeefbff6da, 0xb, 0xc00003c700, 0x40, 0x0, 0x0, 0xc000116f70)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:394 +0xfa
main.runFile(0xc000354000, 0x7ffeefbff6da, 0xb, 0xc00007e300, 0x1)
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:123 +0xae
main.run(0xc0000a21a0, 0x1, 0x1, 0x13, 0x13)
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:89 +0x7e5
main.main()
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:133 +0x479
```

**Comment by mpl** [comment]
And probably related:

```go
package main

import "fmt"

func main() {
	var a interface{}
	a = 2
	fmt.Println(&a)
}
```

gives:

```console
2
```

instead of:

```console
0xc000010200
```
